# Generated by Django 4.2.5 on 2023-09-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=20)),
                ('segundo_nome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
                ('apelido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('quantidade_leitores', models.IntegerField()),
                ('existe_no_sistema', models.BooleanField()),
                ('id_admnistrador', models.ForeignKey(on_delete=models.SET(-1), to='MyBook.administrador')),
                ('id_editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBook.editora')),
            ],
        ),
        migrations.CreateModel(
            name='Livros_Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_lido', models.CharField(max_length=45)),
                ('livro_favorito', models.CharField(max_length=45)),
                ('livro_em_progresso', models.CharField(max_length=45)),
                ('livro_pretende_ler', models.CharField(max_length=45)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBook.livro')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBook.leitor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='livros_leitor',
            constraint=models.UniqueConstraint(fields=('cpf', 'ISBN'), name='cpf_e_ISBN'),
        ),
    ]
