# Generated by Django 4.2.5 on 2023-09-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros_leitor',
            name='livro_em_progresso',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='livros_leitor',
            name='livro_favorito',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='livros_leitor',
            name='livro_lido',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='livros_leitor',
            name='livro_pretende_ler',
            field=models.BooleanField(),
        ),
    ]
